name: Prepare Release

on:
  push:
    tags:
    - '*'

env:
  FOUNDRY_PROFILE: ci

permissions:
  contents: write

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge build

      - name: Prepare Release
        run: |
          script/prepare-release.sh
        env:
          CODE_JAR: ${{ vars.CODE_JAR }}
          RPC_URL: ${{ vars.SEPOLIA_RPC_URL }}

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release/Sleuth.json,release/Sleuth.sol,release/contracts.json,release/sleuth@*"
          bodyFile: "release/RELEASE.md"
          allowUpdates: true
